### ISSUE TITLE
Tabs aren't actually saved in localStorage (or anywhere else)

### ISSUE THREAD

**Issue by Nezteb** [pazsea/stash-tabs#1]
[The code uses `localStorage` (which is undefined)](https://github.com/pazsea/stash-tabs/blob/8631a4215107cdddeb09640c783d584ace876524/webviews/components/Sidebar.svelte#L12) as if it were running in a browser, [which isn't the case](https://github.com/Microsoft/vscode/issues/66207#issuecomment-452425218).

Stash some tabs, close the window, reopen the window, and the stashed tabs are gone.

How to store data in a VS Code extension:
* https://code.visualstudio.com/api/extension-guides/webview#getstate-and-setstate
* https://code.visualstudio.com/api/extension-guides/webview#serialization
* https://www.chrishasz.com/blog/2020/07/28/vscode-how-to-use-local-storage-api/

**Comment by pazsea** [comment]
I can't figure out how to do this in a `vscode.WebviewWebview`. The documentation is for a `vscode.WebviewPanel`... Is there anything called a `WebviewSerializer` or something like that? Any tips for me?

**Comment by pazsea** [comment]
I chose the `retainContextWhenHidden` route. Hopefully this is resolved.
